version: '3.0'

services:
  grafana:
    container_name: 'grafana-hetzner-cloud-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.2.5}
    environment:
      HETZNER_API_TOKEN: ${HETZNER_API_TOKEN}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-hetzner-cloud-datasource,
      - ./provisioning:/etc/grafana/provisioning
